project_id = "wfzjcklrdevhblcuxaoq"

[functions.generate-qr-code]
verify_jwt = true

[functions.scheduled-summaries]
verify_jwt = false

[functions.check-whatsapp-status]
verify_jwt = false

[functions.disconnect-whatsapp]
verify_jwt = true

[functions.fetch-groups]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.trigger-summaries]
verify_jwt = true

[functions.send-group-summary]
verify_jwt = false

[functions.manual-send-summary]
verify_jwt = true